# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Deventra.WTOP
PackageVersion: 3.2.3
InstallerType: wix
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- wtop
Dependencies:
  PackageDependencies:
  - PackageIdentifier: namazso.PawnIO
    MinimumVersion: 2.2.0
ElevationRequirement: elevatesSelf
Installers:
- MinimumOSVersion: 10.0.10240.0
  Architecture: x64
  InstallerUrl: https://deventra.ru/downloads/wtop/3.2.3/WTOP-3.2.3-x64.msi
  InstallerSha256: 928DD37ADA7D8ACA396508A1ECB7EC265D8F2213B8963BECE47C9E2B5B3E1184
  InstallerSwitches:
    Silent: /qn /norestart
    SilentWithProgress: /qn /norestart
  ProductCode: '{12938200-DCF7-4C49-9CB2-25C54BD47265}'
  AppsAndFeaturesEntries:
  - DisplayName: WTOP
    Publisher: Deventra Software
    ProductCode: '{12938200-DCF7-4C49-9CB2-25C54BD47265}'
    UpgradeCode: '{B7159E81-A579-4852-9C2F-2A7CF630E73D}'
    InstallerType: wix
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Deventra\WTop'
ManifestType: installer
ManifestVersion: 1.12.0
