# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Deventra.WTOP
PackageVersion: 3.2.4
InstallerType: wix
Scope: machine
ElevationRequirement: elevatesSelf
InstallModes:
  - silent
  - silentWithProgress
UpgradeBehavior: install
Commands:
  - wtop
Dependencies:
  PackageDependencies:
    - PackageIdentifier: namazso.PawnIO
      MinimumVersion: 2.2.0
Installers:
  - Architecture: x64
    InstallerUrl: https://deventra.ru/downloads/wtop/3.2.4/WTOP-3.2.4-x64.msi
    InstallerSha256: FF0F78B5660F06FB53A72CFECBB4A617C5923C0D8F0D1A7CC3623899190080E0
    ProductCode: '{8E300479-0378-4D88-8369-F256D2EA8EC7}'
    MinimumOSVersion: 10.0.10240.0
    InstallerSwitches:
      Silent: /qn /norestart
      SilentWithProgress: /qn /norestart
    AppsAndFeaturesEntries:
      - DisplayName: WTOP
        Publisher: Deventra Software
        ProductCode: '{8E300479-0378-4D88-8369-F256D2EA8EC7}'
        UpgradeCode: '{B7159E81-A579-4852-9C2F-2A7CF630E73D}'
        InstallerType: wix
    InstallationMetadata:
      DefaultInstallLocation: '%ProgramFiles%\\Deventra\\WTop'
ManifestType: installer
ManifestVersion: 1.12.0
